version: "3"
services:
  eureka:
    build: ../microservice/microservice-eureka-server
    ports:
      - "8761:8761"

  config:
    build: ../microservice/microservice-config-server
    links:
      - eureka
    volumes:
      - ../config/:/root/config

  user:
    build: ../microservice/microservice-user
    links:
      - eureka

  security:
    build: ../microservice/microservice-security
    links:
      - eureka
      - mysql
      - kafka

  contact:
    build: ../microservice/microservice-contact
    links:
      - eureka
      - config
      - mysql
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user:3:1"

  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 6060:8080

  message:
    build: ../microservice/microservice-message
    ports:
      - "8079:8080"
    links:
      - eureka
      - cassandra
      - redis
      - rabbitmq
      - mysql
    networks:
      - chatapp_default

  cassandra:
    # image: "cassandra:3.0"
    build: ./cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_KEYSPACE=db_messages
    networks:
      - chatapp_default
      
  redis:
    image: redis:3.0.6
    ports:
      - "6379:6379"
    networks:
      - chatapp_default

  redis-commander:
    image: rediscommander/redis-commander
    links:
      - redis
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "7070:8081"
    networks:
      - chatapp_default

  rabbitmq:
    build: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    networks:
      - chatapp_default

  zuul:
    build: ../microservice/microservice-zuul-server
    links:
      - eureka
    ports:
      - "8080:8080"

  chatapp:
    build: ../client/web/chatapp
    links:
      - zuul
      - security
      - message
      - contact
    ports:
      - "8000:80"

  # storage:
  #   build: ../microservice/microservice-storage
  #   links:
  #     - eureka
  #     - config
  #     - mysql

  # turbine:
  #   build: ../microservice/microservice-turbine-server
  #   links:
  #     - eureka
  #   ports:
  #     - "8989:8989"

networks:
  chatapp:
    driver: bridge