version: "3"
services:
  eureka:
    build: ../microservice/microservice-eureka-server
    ports:
      - "8761:8761"

  user:
    build: ../microservice/microservice-user
    links:
      - eureka

  security:
    build: ../microservice/microservice-security
    links:
      - eureka
      - mysql
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  message:
    build: ../microservice/microservice-message
    ports:
      - "8079:8080"
    links:
      - eureka
      - cassandra
      - redis
      - rabbitmq
      - mysql
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  group:
    build: ../microservice/microservice-group
    links:
      - eureka

  filemanagement:
    build: ../microservice/microservice-file-management
    links:
      - eureka
      - kafka
      - mysql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  filestorage:
    build: ../microservice/microservice-file-storage
    links:
      - eureka
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  zuul:
    build: ../microservice/microservice-zuul-server
    links:
      - eureka
    ports:
      - "8080:8080"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  turbine:
    build: ../microservice/microservice-turbine-server
    links:
      - eureka
    # ports:
    #   - "8989:8989"

  chatapp:
    build: ../client/web/chatapp
    links:
      - zuul
      - security
      - message
    ports:
      - "8000:80"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "file:5:1"

  redis:
    image: redis:3.0.6
    # ports:
    #   - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    links:
      - redis
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "7070:8081"

  cassandra:
    image: "cassandra:3.0"
    # ports:
    #   - 9042:9042

  rabbitmq:
    build: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 6060:8080
