services:
  zookeeper:
    image: zookeeper
    tmpfs: "/datalog"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user:3:1"

  mysql:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
     - 3306:3306
      

  adminer:
    image: adminer
    ports:
      - 6060:8080

  cassandra:
    image: "cassandra:4"
    ports:
      - 9042:9042
      
  sample-data-cassandra:
    image: cassandra:4
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/init.sh"]
    volumes:
      - ./cassandra/init.sh:/init.sh
    environment:
      - CASSANDRA_KEYSPACE=db_messages
      
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"

  rabbitmq:
    build: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

networks:
  default:
    driver: bridge