version: "3"
services:
  eureka:
    build: ../microservice/microservice-eureka-server
    ports:
      - "8761:8761"

  config:
    build: ../microservice/microservice-config-server
    links:
      - eureka
    volumes:
      - ../config/:/root/config

  user:
    build: ../microservice/microservice-user
    links:
      - eureka

  security:
    build: ../microservice/microservice-security
    links:
      - eureka
      - mysql
      - kafka

  contact:
    build: ../microservice/microservice-contact
    links:
      - eureka
      - config
      - mysql
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user:3:1"

  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 6060:8080

networks:
  chatapp:
    driver: bridge
