chatapp:
  relay:
    host: rabbitmq
    port: 61613
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        boot:
          actuate:
            trace:
              WebRequestTraceFilter: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: true
security:
  basic:
    enabled: false
server:
  port: 8080
spring:
  application:
    name: message
  cloud:
    refresh:
      refreshable: none
  datasource:
    url: jdbc:mysql://mysql/db_security?useSSL=false
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    redis:
      repositories:
        enabled: true
    cassandra:
      contact-points: cassandra
      keyspace-name: db_messages
      username: cassandra
      password: cassandra
      port: 9042
  session:
    store-type: redis  
  messages:
    cache-seconds: 0
  redis:
    host: redis
    port: 6379

security.headers.cache: false 
server.session.timeout: 600