services:
  eureka:
    build: ../microservice/microservice-eureka-server
    ports:
      - "8761:8761"

  config:
    build: ../microservice/microservice-config-server
    links:
      - eureka
    volumes:
      - ../config/:/root/config

  user:
    build: ../microservice/microservice-user
    links:
      - eureka

  security:
    build: ../microservice/microservice-security
    links:
      - eureka
      - mysql
      - kafka

  contact:
    build: ../microservice/microservice-contact
    links:
      - eureka
      - config
      - mysql
      - kafka

  storage:
    build: ../microservice/microservice-storage
    links:
      - eureka
      - config
      - mysql

  turbine:
    build: ../microservice/microservice-turbine-server
    links:
      - eureka
    ports:
      - "8989:8989"

  zookeeper:
    image: zookeeper

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user:3:1"

  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 6060:8080

  message:
    build: ../microservice/microservice-message
    ports:
      - "8079:8080"
    links:
      - eureka
      - cassandra
      - redis
      - rabbitmq
      - mysql

  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"

  sample-data-cassandra:
    image: cassandra:4
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/init.sh"]
    volumes:
      - ./cassandra/init.sh:/init.sh
    environment:
      - CASSANDRA_KEYSPACE=db_messages
      
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    links:
      - redis
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "7070:8081"

  rabbitmq:
    build: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

  zuul:
    build: ../microservice/microservice-zuul-server
    links:
      - eureka
    ports:
      - "8080:8080"

  chatapp:
    build: ../client/web/chatapp
    links:
      - zuul
      - security
      - message
      - contact
    ports:
      - "8000:80"