services:
  message:
    build: ../microservice/microservice-message
    ports:
      - "8079:8080"
    links:
      - eureka
      - cassandra
      - redis
      - rabbitmq
      - mysql
    networks:
      - chatapp_default_test

  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"
    networks:
      - chatapp_default_test

  sample-data-cassandra:
    image: cassandra:4
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/init.sh"]
    volumes:
      - ./cassandra/init.sh:/init.sh
    environment:
      - CASSANDRA_KEYSPACE=db_messages
    networks:
      - chatapp_default_test
      
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    networks:
      - chatapp_default_test

  redis-commander:
    image: rediscommander/redis-commander
    links:
      - redis
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "7070:8081"
    networks:
      - chatapp_default_test

  rabbitmq:
    build: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    networks:
      - chatapp_default_test

  zuul:
    build: ../microservice/microservice-zuul-server
    links:
      - eureka
    ports:
      - "8080:8080"

  chatapp:
    build: ../client/web/chatapp
    links:
      - zuul
      - security
      - message
      - contact
    ports:
      - "8000:80"
  

networks:
  chatapp_default_test:
    external: true
