chatapp:
  relay:
    host: rabbitmq
    port: 61613
finbertmds:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: finbertmdsSecretKey
    firebaseNotificationTopic: chatapp
    firebaseServerKey: AAAAWIYGAfA:APA91bEKr8LipSv9XG9T8yE0Dfadjf9o8175N25KXKUoBXfioMxep1j0IJBUKkY6SnKExN_DJFepCIxac3oAqbJ_62qMCSHZDfHCA0rAA5aggazhxIdVkLVSG7ukMo6kS3EzlFnzJDUh
    firebase-configuration-file: fcm/config.json  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        boot:
          actuate:
            trace:
              WebRequestTraceFilter: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: true
security:
  basic:
    enabled: false
server:
  port: 8080
spring:
  application:
    name: message
  datasource:
    url: jdbc:mysql://mysql/db_security?useSSL=false
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    cassandra:
      contact-points: cassandra
      keyspace-name: db_messages
      username: cassandra
      password: cassandra
      port: 9042
      local-datacenter: datacenter1
    redis:
      repositories:
        enabled: true
  session:
    store-type: redis  
  messages:
    cache-seconds: 0
  redis:
    host: redis
    port: 6379

security.headers.cache: false 
server.session.timeout: 600