server:
  port: 8080
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health    
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
        enabled: true
  semaphore:
    max-semaphores: 500

finbertmds:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: finbertmdsSecretKey

spring:
  application:
    name: zuul
  datasource:
    initialization-mode: always
    password: root
    url: jdbc:mysql://mysql/db_security?useSSL=false
    username: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
  file: /logs/zuul-json.log
