server:
  port: 8080
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health    
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

zuul:
  sensitiveHeaders: 
  host:
    connect-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
        enabled: true
  semaphore:
    max-semaphores: 500

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

finbertmds:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: finbertmdsSecretKey

spring:
    datasource:
        initialization-mode: always
        password: root
        url: jdbc:mysql://mysql/db_security?useSSL=false
        username: root
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
