name: turbine server
on:
  push:
    tags:
      - "v*"
    branches: 
      - master
    paths:
    - "microservice/microservice-turbine-server/**"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: turbine server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create Docker images 
        run: |
          cd scripts && ./ciRebuildServices.sh turbine-server
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag images
        run: |
          docker tag chatapp_turbine ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_turbine:latest
      - name: Push images to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_turbine:latest