name: message
on:
  push:
    tags:
      - "v*"
    branches:
      - master
      - develop
    paths:
      - "microservice/microservice-message/**"
      - ".github/workflows/build-message.yml"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: message
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create Docker images
        run: |
          cd scripts && ./ciRebuildServices.sh message
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag images
        run: |
          docker tag docker.io/library/chatapp_message ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_message:latest
      - name: Push images to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_message:latest
