name: eureka server
on:
  push:
    branches: 
      - develop
    paths:
    - "microservice/microservice-eureka-server/**"
jobs:
  push_to_registry:
    name: eureka server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create Docker images 
        run: |
          cd scripts && ./ciRebuildServices.sh eureka-server
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag images
        run: |
          docker tag chatapp_eureka ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_eureka:latest
      - name: Push images to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_eureka:latest