name: message
on:
  push:
    tags:
      - "v*"
    branches:
      - master
    paths:
      - "microservice/microservice-message/**"
      - ".github/workflows/build-message.yml"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: message
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "gradle"
      - name: Create Docker images
        run: |
          cd scripts && ./ciRebuildServices.sh message
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag images
        run: |
          docker tag docker.io/library/chatapp-message ${{ secrets.DOCKERHUB_USERNAME }}/chatapp-message:latest
      - name: Push images to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatapp-message:latest
