name: chatapp web
on:
  push:
    tags:
      - "v*"
    branches:
      - master
    paths:
      - "client/web/chatapp/**"
      - ".github/workflows/build-chatapp-web.yml"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: chatapp web
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: |
          cd client/web/chatapp && npm install
      - name: Create Docker images
        run: |
          cd scripts && ./ciRebuildServices.sh chatapp
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag images
        run: |
          docker tag docker.io/library/chatapp-chatapp ${{ secrets.DOCKERHUB_USERNAME }}/chatapp-chatapp:latest
      - name: Push images to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatapp-chatapp:latest
