name: chatapp web
on:
  push:
    tags:
      - "*"
    branches: 
      - master
    paths:
    - "client/web/chatapp/**"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: chatapp web
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: |
          cd client/web/chatapp && npm install
      - name: Create Docker images 
        run: |
          cd scripts && ./ciRebuildServices.sh chatapp
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag images
        run: |
          docker tag chatapp_chatapp ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_chatapp:latest
      - name: Push images to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatapp_chatapp:latest